// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using librarian_workplace_DAL.EF;

#nullable disable

namespace librarian_workplace_DAL.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20230818121747_UpdateColumnDateBorrowed")]
    partial class UpdateColumnDateBorrowed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("librarian_workplace_DAL.Entities.Book", b =>
                {
                    b.Property<Guid>("ArticleNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("article_number");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("author");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("inset_date");

                    b.Property<int>("InstancesNumber")
                        .HasColumnType("int")
                        .HasColumnName("instances_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("publication_date");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("update_date");

                    b.HasKey("ArticleNumber");

                    b.ToTable("book", (string)null);
                });

            modelBuilder.Entity("librarian_workplace_DAL.Entities.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_added");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_updated");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fio");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id");

                    b.ToTable("reader", (string)null);
                });

            modelBuilder.Entity("librarian_workplace_DAL.Entities.ReaderBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuleNumber")
                        .HasColumnType("UUID")
                        .HasColumnName("articule_number");

                    b.Property<DateTime>("DateBorrowed")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_borrowed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("UUID")
                        .HasColumnName("reader_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticuleNumber");

                    b.HasIndex("ReaderId");

                    b.ToTable("reader_book", (string)null);
                });

            modelBuilder.Entity("librarian_workplace_DAL.Entities.ReaderBook", b =>
                {
                    b.HasOne("librarian_workplace_DAL.Entities.Book", "Book")
                        .WithMany("ReaderBooks")
                        .HasForeignKey("ArticuleNumber")
                        .IsRequired()
                        .HasConstraintName("book_and_reader_book_id_fkey");

                    b.HasOne("librarian_workplace_DAL.Entities.Reader", "Reader")
                        .WithMany("ReaderBooks")
                        .HasForeignKey("ReaderId")
                        .IsRequired()
                        .HasConstraintName("reader_and_reader_book_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("librarian_workplace_DAL.Entities.Book", b =>
                {
                    b.Navigation("ReaderBooks");
                });

            modelBuilder.Entity("librarian_workplace_DAL.Entities.Reader", b =>
                {
                    b.Navigation("ReaderBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
